"""Localized display labels for catalog products.

The Polish name from ``Table3.json`` remains the stable calculation key.  This
module changes only what the mobile interface displays, so calculations,
entitlements, recent selections and image resolution keep using canonical data.
"""

PRODUCT_LABELS_EN: dict[str, str] = {
    # Vegetables
    "Bakłażan": "Eggplant",
    "Bataty": "Sweet potatoes",
    "Bób": "Broad beans",
    "Brokuły": "Broccoli",
    "Brukiew": "Rutabaga",
    "Brukselka": "Brussels sprouts",
    "Buraki": "Beets",
    "Cebula": "Onion",
    "Cebula suszona": "Dried onion",
    "Chrzan": "Horseradish",
    "Czosnek": "Garlic",
    "Dynia": "Pumpkin",
    "Endywia": "Endive",
    "Fasola szparagowa": "Green beans",
    "Grzyby": "Mushrooms",
    "Groszek zielony": "Green peas",
    "Imbir": "Ginger",
    "Jarmuż": "Kale",
    "Kalafior": "Cauliflower",
    "Kalarepa": "Kohlrabi",
    "Kapusta": "Cabbage",
    "Kapusta liściasta": "Collard greens",
    "Kabaczek": "Summer squash",
    "Kabaczek zimowy": "Winter squash",
    "Karczochy": "Artichokes",
    "Kukurydza cukrowa": "Sweet corn",
    "Liście rzepy": "Turnip greens",
    "Marchew": "Carrots",
    "Ogórki": "Cucumbers",
    "Okra": "Okra",
    "Papryka (słodka, główna odmiana)": "Sweet peppers (main variety)",
    "Papryka liofilizowana": "Freeze-dried peppers",
    "Pasternak": "Parsnips",
    "Pietruszka": "Parsley",
    "Pomidory dojrzałe": "Ripe tomatoes",
    "Pomidory zielone": "Green tomatoes",
    "Pory": "Leeks",
    "Rabarbar": "Rhubarb",
    "Rukiew wodna": "Watercress",
    "Rzepa": "Turnips",
    "Rzodkiewka": "Radishes",
    "Salsify": "Salsify",
    "Sałata lodowa": "Iceberg lettuce",
    "Seler korzeniowy": "Celeriac",
    "Seler naciowy": "Celery",
    "Słodki ziemniak": "Sweet potato",
    "Szparagi": "Asparagus",
    "Szpinak": "Spinach",
    "Topinambur": "Jerusalem artichoke",
    "Ziemniaki": "Potatoes",
    # Fruit
    "Agrest": "Gooseberries",
    "Ananas": "Pineapple",
    "Arbuz": "Watermelon",
    "Awokado": "Avocado",
    "Banany": "Bananas",
    "Brzoskwinie świeże": "Fresh peaches",
    "Brzoskwinie suszone": "Dried peaches",
    "Cytryny": "Lemons",
    "Daktyle suszone": "Dried dates",
    "Figi świeże": "Fresh figs",
    "Figi suszone": "Dried figs",
    "Granaty": "Pomegranates",
    "Grejpfrut": "Grapefruit",
    "Gruszki": "Pears",
    "Jagody": "Blueberries",
    "Jabłka świeże": "Fresh apples",
    "Jabłka suszone": "Dried apples",
    "Jeżyny": "Blackberries",
    "Kantalupa": "Cantaloupe",
    "Limonka": "Lime",
    "Maliny": "Raspberries",
    "Mandarynki": "Mandarins",
    "Mango": "Mango",
    "Melon kasaba": "Casaba melon",
    "Melon miodowy": "Honeydew melon",
    "Morele": "Apricots",
    "Nektaryny": "Nectarines",
    "Oliwki": "Olives",
    "Persymona": "Persimmon",
    "Pigwy": "Quinces",
    "Pomarańcze": "Oranges",
    "Porzeczka czarna": "Blackcurrants",
    "Porzeczki czerwone i białe": "Red and white currants",
    "Rodzynki": "Raisins",
    "Suszone śliwki": "Prunes",
    "Śliwki": "Plums",
    "Truskawki": "Strawberries",
    "Wiśnie kwaśne": "Sour cherries",
    "Wiśnie słodkie": "Sweet cherries",
    "Winogrona amerykańskie": "American grapes",
    "Winogrona europejskie": "European grapes",
    "Żurawina": "Cranberries",
    # Fish and seafood
    "Dorsz": "Cod",
    "Łupacz": "Haddock",
    "Halibut": "Halibut",
    "Śledź wędzony": "Smoked herring",
    "Makrela atlantycka": "Atlantic mackerel",
    "Okoń": "Perch",
    "Mintaj atlantycki": "Atlantic pollock",
    "Łosoś różowy": "Pink salmon",
    "Tuńczyk błękitnopłetwy": "Bluefin tuna",
    "Witlinek": "Whiting",
    "Małże": "Mussels",
    "Homar amerykański": "American lobster",
    "Ostrygi": "Oysters",
    "Przegrzebki": "Scallops",
    "Krewetki": "Shrimp",
    # Beef and veal
    "Mostek wołowy": "Beef brisket",
    "Tusza wołowa, gatunek I": "Beef carcass, grade I",
    "Tusza wołowa, gatunek II": "Beef carcass, grade II",
    "Wątróbka wołowa": "Beef liver",
    "Żeberka wołowe (6-12)": "Beef ribs (6-12)",
    "Wołowina, udziec, pełny kawałek, chudy i tłusty": (
        "Beef round, whole cut, lean and fat"
    ),
    "Wołowina, udziec, pełny kawałek, chudy": (
        "Beef round, whole cut, lean"
    ),
    "Polędwica wołowa, chuda": "Beef tenderloin, lean",
    "Stek z antrykotu, chudy": "Ribeye steak, lean",
    "Stek T-bone, chudy": "T-bone steak, lean",
    "Polędwica wołowa, chuda2": "Beef tenderloin, lean (2)",
    "Cielęcina, chuda": "Veal, lean",
    # Pork and sausages
    "Boczek surowy": "Raw bacon",
    "Boczek wędzony": "Smoked bacon",
    "Podgardle": "Pork jowl",
    "Tusza wieprzowa": "Pork carcass",
    "Szynka wieprzowa, cała, chuda": "Pork ham, whole, lean",
    "Szynka wieprzowa, wiejska, chuda": "Country-style pork ham, lean",
    "Łopatka wieprzowa, cała, chuda": "Pork shoulder, whole, lean",
    "Kiełbasa Braunschweiger": "Braunschweiger sausage",
    "Kiełbasa frankfurterka": "Frankfurter sausage",
    "Kiełbasa polska": "Polish sausage",
    "Kiełbasa wieprzowa": "Pork sausage",
    "Kiełbasa włoska": "Italian sausage",
    "Kiełbasa wędzona": "Smoked sausage",
    # Poultry, eggs and lamb
    "Indyk": "Turkey",
    "Kaczka": "Duck",
    "Kurczak": "Chicken",
    "Białko jaja": "Egg white",
    "Białko suszone": "Dried egg white",
    "Całe jajko": "Whole egg",
    "Całe jajko suszone": "Dried whole egg",
    "Żółtko": "Egg yolk",
    "Żółtko solone": "Salted egg yolk",
    "Żółtko słodzone": "Sweetened egg yolk",
    "Jagnięcina (różne kawałki), chuda": "Lamb (assorted cuts), lean",
    "Udziec jagnięcy, chudy": "Leg of lamb, lean",
    # Dairy and cheese
    "Masło": "Butter",
    "Camembert": "Camembert",
    "Cheddar": "Cheddar",
    "Gouda": "Gouda",
    "Limburger": "Limburger",
    "Mozzarella": "Mozzarella",
    "Parmezan, twardy": "Parmesan, hard",
    "Roquefort": "Roquefort",
    "Ser szwajcarski": "Swiss cheese",
    "Ser topiony amerykański": "American processed cheese",
    "Serek śmietankowy": "Cream cheese",
    "Serek wiejski, bez śmietany": "Cottage cheese, uncreamed",
    "Pół na pół": "Half-and-half",
    "Śmietana stołowa": "Table cream",
    "Śmietanka kremówka": "Heavy cream",
    "Czekoladowe": "Chocolate ice cream",
    "Truskawkowe": "Strawberry ice cream",
    "Waniliowe": "Vanilla ice cream",
    "Mleko odparowane": "Evaporated milk",
    "Mleko odtłuszczone": "Skim milk",
    "Mleko odtłuszczone w proszku": "Skim milk powder",
    "Mleko pełne": "Whole milk",
    "Mleko pełne w proszku": "Whole milk powder",
    "Mleko zagęszczone, słodzone": "Sweetened condensed milk",
    "Serwatka kwaśna w proszku": "Acid whey powder",
    "Serwatka słodka w proszku": "Sweet whey powder",
    # Nuts and sweets
    "Migdały": "Almonds",
    "Orzechy laskowe": "Hazelnuts",
    "Orzechy włoskie": "Walnuts",
    "Orzeszki ziemne, prażone z solą": "Peanuts, roasted and salted",
    "Orzeszki ziemne, surowe": "Raw peanuts",
    "Pekany": "Pecans",
    "Czekolada mleczna": "Milk chocolate",
    "Krówka waniliowa": "Vanilla fudge",
    "Kruche ciastka z orzeszkami": "Peanut shortbread cookies",
    "Pianki Marshmallow": "Marshmallows",
    # Juices and drinks
    "Cola": "Cola",
    "Mleko czekoladowe, 2% tłuszczu": "Chocolate milk, 2% fat",
    "Napój cytrynowo-limonkowy": "Lemon-lime drink",
    "Napój imbirowy": "Ginger ale",
    "Napój owocowy": "Fruit drink",
    "Napój pomarańczowy": "Orange drink",
    "Napój śmietankowy": "Cream soda",
    "Napój winogronowy": "Grape drink",
    "Napój żurawinowo-jabłkowy": "Cranberry-apple drink",
    "Napój żurawinowo-winogronowy": "Cranberry-grape drink",
    "Piwo korzenne": "Root beer",
    "Sok ananasowy, niesłodzony": "Pineapple juice, unsweetened",
    "Sok grejpfrutowy, słodzony": "Grapefruit juice, sweetened",
    "Sok jabłkowy, niesłodzony": "Apple juice, unsweetened",
    "Sok pomarańczowy": "Orange juice",
    "Sok pomidorowy": "Tomato juice",
    "Sok śliwkowy": "Prune juice",
    "Sok winogronowy, niesłodzony": "Grape juice, unsweetened",
    "Sok z cytryny": "Lemon juice",
    "Sok z limonki, niesłodzony": "Lime juice, unsweetened",
    "Woda gazowana": "Carbonated water",
    # Miscellaneous
    "Drożdże piekarnicze, sprasowane": "Compressed baker's yeast",
    "Miód": "Honey",
    "Popcorn, prażony na powietrzu": "Air-popped popcorn",
    "Popcorn, prażony na oleju": "Oil-popped popcorn",
    "Syrop klonowy": "Maple syrup",
    "Chleb pszenny": "Wheat bread",
    "Płyta TKT": "TKT panel",
}


def display_product(language: str, product_name: str | None) -> str:
    """Return a localized label without changing the canonical product name."""

    if not product_name:
        return ""
    if language == "en":
        return PRODUCT_LABELS_EN.get(product_name, product_name)
    return product_name


__all__ = ["PRODUCT_LABELS_EN", "display_product"]
